version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: adbalancer-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: balancer
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: adbalancer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: adbalancer-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://balancer:secretpassword@db:5432/adbalancer_db?schema=public
      - ADMIN_TOKEN=sua_senha_super_secreta_aqui

volumes:
  postgres_data:
